name: Continuous Integration
run-name: ${{ github.actor }} is running CI check 🚀
on:
  pull_request:
    branches:
      - main

env:
  NO_FLIPPER: 1

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: NodeJS setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'

      - name: Install yarn dependencies
        run: yarn install

      - name: TypeScript check
        run: yarn typescript

      - name: ESLint check
        run: yarn lint

      - name: Jest tests
        run: yarn test

  e2e-tests-android:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    outputs:
      apk: android/app/build/outputs/apk/release/app-release.apk

    steps:
    - name: Check out code repository
      uses: actions/checkout@v4

    - name: NodeJS setup
      uses: actions/setup-node@v4
      with:
        node-version-file: '.tool-versions'

    - name: Install yarn dependencies
      run: yarn install

    - name: Create env file
      run: |
        touch .env
        echo OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }} >> .env

    - name: build Android release apk
      run: yarn android:build:release

    - uses: mobile-dev-inc/action-maestro-cloud@v1.7.0
      with:
        api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
        app-file: android/app/build/outputs/apk/release/app-release.apk

  e2e-tests-ios:
    runs-on: macOS-latest
    needs: [continuous-integration]

    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: NodeJS setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'

      - name: Install yarn dependencies
        run: yarn install

      - name: Install cocoapods dependencies
        run: cd ios && pod install

      - name: Create env file
        run: |
          touch .env
          echo OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }} >> .env

      - name: build iOS debug apk
        run: yarn ios:build:debug

      - uses: mobile-dev-inc/action-maestro-cloud@v1.7.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: build/WeatherApp.app
